### ISSUE TITLE
No more works with right-click button or `CTRL + click`

### ISSUE THREAD

**Issue by tunnckoCore** [github-linker/chrome-extension#47]
After `v3.8.0` bump. Which makes it unusable, imo.

Chrome 43.0.2357.130, ArchLinux.

**Comment by stefanbuck** [comment]
Thanks, I'll fix it tonight

**Comment by stefanbuck** [comment]
<kbd>CTRL</kbd> + click is fixed in `v.3.8.2`, but right-click isn't anymore supported because of change from a static map list to a resolver api. For more details check out the release notes from [v.3.8.0](https://github.com/github-linker/chrome-extension/releases/tag/v.3.8.0)

**Comment by tunnckoCore** [comment]
@stefanbuck it seems it's not fixed. 

Is there any way to use v3.7.x extension?

**Comment by stefanbuck** [comment]
Damn. You can build the previous version by yourself https://github.com/github-linker/chrome-extension/commit/06b0d337ffd8a39231c6b5cfc98a0df2276d2a75. But I'm interested to fix it issue :wink:

**Comment by tunnckoCore** [comment]
Okey, i'll try :)

**Comment by stefanbuck** [comment]
I found the problem and will release a fix this evening. 

Cheers

**Comment by stefanbuck** [comment]
Please check it if it is working in `3.8.3` :fingercrossed:

**Comment by tunnckoCore** [comment]
not released/published

**Comment by stefanbuck** [comment]
It is 
![w zgxleotalzaaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/1393946/9554913/c500c4d6-4dc9-11e5-9b36-9971343dab49.png)

**Comment by tunnckoCore** [comment]
There's no github release and chrome didn't notify me that there have updates.

**Comment by stefanbuck** [comment]
Notifications are only there for minor and major releases not for bugfixes. I will write release notes later this evening.

**Comment by tunnckoCore** [comment]
Oo, okey. Yea ctrl + click works.

**Comment by tunnckoCore** [comment]
@stefanbuck not work when reviewing some file.

**Comment by stefanbuck** [comment]
Please send me the URL so I can take a look on it. Thanks

**Comment by tunnckoCore** [comment]
Firstly the extension worked as expect - when browsing github files and when looking READMEs. Now nothing. It's not specific file.

**Comment by stefanbuck** [comment]
Strange, I will check it.

**Comment by stefanbuck** [comment]
@tunnckoCore Did you build the previous version by yourself? If so, please make sure that there is only one GitHub-Linker extension installed / active in your browser.
